# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('opening_from', models.TimeField(verbose_name='Open from')),
                ('opening_to', models.TimeField(verbose_name='Open to')),
            ],
        ),
    ]
