# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='logo',
            field=models.ImageField(blank=True, default='/meals/meal_default.jpeg', upload_to='meals/'),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, default='Normal size', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.Category'),
        ),
    ]
