# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='logo',
            field=models.ImageField(blank=True, default='/meals/meal_default.jpeg', upload_to='meals/'),
        ),
    ]
