# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_meal_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, default='Normal size', max_length=50),
        ),
    ]
