# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Canceled'), (2, 'Ordered'), (3, 'Delivered')], default=0)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baskets.Basket')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Meal')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='menus.Topping')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set([('owner', 'created_at')]),
        ),
    ]
