# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=140, upload_to='profiles/'),
        ),
    ]
